- Dockerfile
- vdb/README.md
- vdb/download.py
I noticed that the **pick_longest** parameter was not in the **ArgumentParser** so I wanted to add that parameter. 
I also noticed **resolve_duplicates** was setting pick_longest to be True as default
>def resolve_duplicates(self, sequences, pick_longest=True, **kwargs):
so pick_longest was only useful when the user specified _pick\_longest=False_. I took this to mean that the most common use case (or the one we would like to encourage) is for users to remove duplicate sequences when they are not necessary.
I changed the parameter to be the opposite, **keep_duplicates**, in hope that it will be more intuitive for the user :)
>python -u vdb/flu_download.py -db vdb -v flu --keep_duplicates
I also deleted some default settings as argparse already sets them as default.
> Parameter modification

- tdb/cdc_upload.py
- tdb/upload.py
- tdb/upload_all.py
This will now set subtype to something passed in from the command line, like `--subtype h3n2`, but if `--subtype` is absent from the command line, it will look for the subtype field within the document. The function `format_subtype` canonicalizes subtype names.
Fixes #51.
> Parse subtype from document field

- flu/download_all.py
- tdb/cdc_upload.py
- tdb/download.py
- tdb/elife_upload.py
- tdb/nimr_upload.py
- tdb/upload.py
`--select` and `--present` were already in `tdb/download.py`. This just makes `--select assay_type:hi` function appropriately. It also pads out `download_all` to download separate datasets to different directories.
Fixes #47.
> Improve downloading of assay_type selections

- download_all.py
The download_all.py script tries to reference deprecated `copy_data` and `augur_path` parameters after each download resulting in an exception. This PR removes those references.
> Removed references to deprecated copy_data and augur_path parameters.

- tdb/concatenate.py
This PR contains a script that will take a set of titer tsvs downloaded from fauna and concatenates them to one master file. Source/passage information is read from file names and added to each entry.
Fixes #76
> Add script to concatenate all titers to one file tracking source/passage

- vdb/download.py
Otherwise it's not possible to specify a useful set of fields on the
command line.  This hasn't been an issue since currently all the
vdb/*_download.py scripts overwrite any passed value with a hardcoded
list of fields.  For a pathogen build system, however, it's useful to
specify these on the command line.
> vdb/download.py: Let --fasta_fields take multiple values

- source-data/flu_fix_location_label.tsv
- source-data/geo_synonyms.tsv
- tdb/upload_all.py
- tdb/vidrl_upload.py
Vic and Yam tables had been failing to upload because the parser was looking for the text "Reference Antigens" in a particular, hard-coded cell of the tables. The formatting of the fluB tables was slightly different, so they were failing that check. This PR fixes the issue by adding both cases, and trying the fluB case after the fluA case. Additionally, adds some minor bugfixes that were discovered while trying to fix this error.
> Fix parsing of VIDRL fluB tables

- vdb/download.py
This PR moves the function `rethinkdb_date_greater` from the end of the `vdb/download.py` to the beginning, so that it is in scope when the download is called. 
This fixes an error when the `--interval` flag was used for virus downloads in which `rethinkdb_date_greater` could not be found by `add_intervals_command`.
@huddlej would you mind taking a look at this just to let me know if this has been moved to the most appropriate location? The (previously broken) command that I have been using to run is:
```
python3 vdb/download.py --database vdb \
--virus flu \
--fasta_fields strain virus accession collection_date region country division \
location passage_category submitting_lab age gender \
--resolve_method split_passage \
--select locus:na lineage:seasonal_h3n2 \
--interval …
```
> Move date selection function

- source-data/cdc_titer_column_map.tsv
- tdb/cdc_upload.py
The CDC is moving to a new table format that includes all titer data.
We should only ingest the titers that are marked reportable.
The new `--filter` option filters for rows where `titer_reportable` is
True and prints the filtered titers to a new TSV with columns that have
been renamed according to `source-data/cdc_titer_column_map.tsv`.
The column names should match previous CDC titer table columns so that
the `cdc_upload` class does not need to be updated.
---
> tdb/cdc_upload: Add filter option for new titers

- tdb/download.py
Adds a header to the titer table output based on the text fields
requested from each record. This change allows users of the resulting
data to easily determine what data they're looking at instead of having
to guess and manually add a header each time they load these data into
pandas, etc.
Although it would be nice to updated Augur's titer model code to use
these headers instead of indexing titer table values by hardcoded column
indices, it looks like Augur should handle the inclusion of a header
column by [skipping the header when its fifth column cannot be converted
to a float](https://github.com/nextstrain/augur/blob/15dfc8bc5c5a570066ddd5601c9aa82e0c1d2b7d/augur/titer_model.py#L72-L75).
Tested locally with WHO titers for HI and FRA assays.
> Include a header in titer tables

- tdb/download.py
Adds two date fields to the list of fields to write out from each titer
record, making exploration of titer data by date substantially easier by
avoiding linking of strain dates to test/reference strains.
In addition to adding these two fields, this commit fixes an annoying
bug in the original titer output where a trailing tab character
effectively creates an empty last column that has to be dealt with
during parsing by pandas, etc.
Tested by downloading WHO titers for HI and FRA data and filtering these data interactively on their assay date and inclusion date values.
> Include assay and inclusion dates for titer data

- builds/ZIKA.md
This reverts most of commit 0e5176a4477d369a380e1d5a89d53f3b2834f966.
An unrelated filename fix (removing "zika_" prefix from filenames) was
left unreverted.
The instructions around compression were the result of being misled by
curl's default of not unwrapping Content-Encoding (i.e. it must be
enabled by using the --compression option).
> Revert "Compensate for automatic compression by nextstrain remote upload

- builds/ZIKA.md
Add the ViPR API call as a alternative programmatic method of retrieving sequences. However, keep the documentation on downloading sequences via the GUI for easier comprehension. 
Possibly test by downloading sequences from GUI, downloading sequences via API call, and run a `diff` on the two files.
> document ViPR API call as an alternative download

- builds/ZIKA.md
Minimum year should be 2013:
https://github.com/nextstrain/fauna/blob/a1e3840cb43f322afc5c6c027a40d383813303ea/builds/ZIKA.md?plain=1#L12
_N/A_
_N/A_
> Fix min year in API call

- builds/MEASLES.md
Add search-and-replace (`sed`) command to drop `.1` and `.2` postfix from accessions.
> preprocess sed command

- builds/DENGUE.md
- builds/MEASLES.md
- builds/ZIKA.md
For the zika, measles, and dengue s3 endpoints; switch from xz and gz to the faster zstd to be consistent with:
* https://github.com/nextstrain/ncov-ingest/pull/345
Filled in details to measles and dengue instructions, to be consistent with zika instructions.
Related to:
* https://github.com/nextstrain/ncov-ingest/pull/345
Related PRs:
* https://github.com/nextstrain/dengue/pull/5
* https://github.com/nextstrain/measles/pull/7
* https://github.com/nextstrain/zika/pull/23
Any proof-reading is welcome! Or edits to the wording.
> docs: zstd

- vdb/avian_flu_download.py
- vdb/avian_flu_upload.py
The avian influenza builds require a few updates to make sure that they are displaying the most complete and accurate metadata. In particular, since the initial build, GISAID has added a metadata field describing whether sequences from animals were sampled from domestic or wild animals, which is a useful annotation to display. Additionally, it would be nice to include author information on the tips, as well as data on originating lab and any linked pubmed references. Finally, for sequences that are pulled into GISAID from public databases, it is nice to be able to link those sequences back to their original, public database accession numbers so that the original data entry can be referenced. This pull request makes a few simple edits in `avian_flu_upload.py` and `avian_flu_download.py` to …
> Avian flu upload additions

- source-data/avian_flu_strain_name_fix.tsv
- source-data/geo_regions.tsv
- source-data/geo_synonyms.tsv
- vdb/avian_flu_upload.py
This pull request includes a series of simple changes to the avian-flu upload protocol to account for a few new features: 
1. GISAID recently began including clade information into the downloadable metadata. This is useful information to download, especially because it includes up to date clade 2.3.4.4 and 2.3.2.1 splits. This pull request includes new download and upload fields for fauna. 
2. I've separated out the strain name fixes into their own file that is distinct from the seasonal flu strain name fixes. The file was getting enormous, and there are some very specific, recurrent errors in the avian flu database that are just easier to deal with on their own. Avian flu strain name fixes are now included in `avian_flu_strain_name_fix.tsv`.
3. I also added a check to print out strains …
> Gisaid clade and download changes

- scripts/delete_records.py
Add a new `--interval` option `delete_records.py` to filter records with date intervals.
This will be used to delete records that uploaded within a certain
date interval in preparation for uploading the latest CDC data¹ and
for merging https://github.com/nextstrain/fauna/pull/131.
Follows the pattern of the `--interval` option for `tdb/download.py` and
uses the `rethinkdb_date_greater` function from `vdb/download.py` to
check for date range in documents.
¹ https://bedfordlab.slack.com/archives/C03KWDET9/p1697750132854499
> Delete records with date intervals

- source-data/cdc_titer_column_map.tsv
- tdb/cdc_upload.py
Fixes a couple of CDC titer upload issues:
- #126 
- #130
- #129 
The `serum_id` and `serum_passage_category` fields are part of the [upload index fields](https://github.com/nextstrain/fauna/blob/bcf3a46e2fee676eb0dec6b69fd406bf5d4bf815/tdb/upload.py#L51), so we will need to delete records from `cdc_tdb/flu` before we can upload data with these new changes. 
- `serum_host` is correctly parsed for "human" and "mouse"
- `serum_passage_category` is correctly parsed for human pool sera
> Fix cdc uploads

- .gitmodules
- RETHINKDB.md
- base/rethink_io.py
- requirements.txt
Require TLS on non-localhost connections
We've enabled TLS for Fauna's RethinkDB server.
The rethinkdb Python module requires a set of CA certificates to trust
and cannot be configured to use the system's default set of trusted CAs.
Use certifi to obtain a reasonable default set of commonly trusted CAs.
Related-to: <https://github.com/nextstrain/private/issues/86>
> TLS support

- vdb/flu_upload.py
Digging through git history and found example of FASTA header that
suggests GISAID did not used to include the "EPI" prefix in their
DNA Accession no. field.¹
This must have changed around October 2023 because we have sequences
with "EPIEPI" accessions for sequences submitted after September 27th 2023.²
This commit changes the ingest to only prefix with "EPI" if the accession
does not already have the prefix.
¹ https://github.com/nextstrain/fauna/blame/f485baa3621002b3ff6f833c743180239a92bf14/vdb/gisaid_flu_upload.py#L281-L282
² https://bedfordlab.slack.com/archives/C03KWDET9/p1700609695217959
> Fix GISAID flu accessions

- requirements.txt
rethinkdb v2.4.10 is broken because it did not include the newly added `looseversion` package to their setup.py.
https://github.com/rethinkdb/rethinkdb-python/issues/309
> requirements: Skip rethinkdb v2.4.10

- builds/ZIKA.md
The old instructions were written for ViPR which became obsolete and was replaced by BV-BRC. The old instructions no longer work and we have since adopted NCBI datasets for downloading sequences and metadata files.
The filtering by length and collection year are already part of the phylogenetic build steps so are no longer a consideration during ingest. 
This PR updates our instructions on how to ingest recent zika data and push to the nextstrain data endpoint. This PR also points to the current phylogenetic build steps.
* https://github.com/nextstrain/fauna/issues/128
> Update zika instructions

- vdb/flu_upload.py
CDC folks flagged that our seasonal flu builds¹ contain a weird submitting lab ("$ins Submitting Name") for many sequences.
I found that these values were coming directly from our FASTA headers in the download from GISAID.² This commit changes our flu upload script to parse the submitting lab from the metadata XLS file instead of the FASTA header since the XLS file contains the correct values.
When we download the sequences with `vdb/flu_download`, the `rethinkdb_download` merge command³ will give preference to the `submitting_lab` of the `flu_viruses` table according to the rethinkdb docs.⁴
> When there is a conflict between field names, preference is given to
> fields in the rightmost object in the argument list.
So to correct the existing sequences within fauna, we just need to …
> vdb/flu_upload: parse `submitting_lab` from XLS

- tdb/crick_upload.py
Looks like Crick has shifted to using a template workbook that includes an extra "comments" sheet which includes instructions on how to use the template. Exclude the "comments" sheet in our processing so that we don't raise unnecessary errors.
> crick_upload: Skip "comments" sheets

- tdb/titer_block.py
- tdb/vidrl_upload.py
First pass for ingesting VIDRL human sera references, focused on 2024 data. 
I'm hoping that ingesting older data should be as simple as updating the VACCINE_MAPPING, but we'll see...
Related to #158
> Ingest VIDRL human sera references

- tdb/vidrl_upload.py
Instead of using the strains recommended by the vaccine composition for the Southern Hemisphere, match to the proxy reference strains that VIDRL provides in their flat files.
Related to https://github.com/nextstrain/fauna/issues/166
> vidrl_upload: Update `VACCINE_MAPPING` to match proxies

- tdb/niid_upload.py
This PR extends the functionality for autodetecting titer blocks (previously implemented for VIDRL Excel files) to **NIID excel files**. By replacing the reliance on hardcoded row and column start and stop coordinates, this enhancement provides greater flexibility and reduces the need for frequent updates when file formats change.
Basically changing from hardcoded row and columns code:
https://github.com/nextstrain/fauna/blob/ecce160b285a1333f00c67730700091651143cbe/tdb/niid_upload.py#L70-L89
To automatically detecting the titer block
https://github.com/nextstrain/fauna/blob/47c06e837b97826461486a1412d076abb6f3952f/tdb/niid_upload.py#L54-L66
This PR reuses the `titer_block.py` functions introduced during  https://github.com/nextstrain/fauna/pull/157, which automatically detect titer …
> Auto-detect column and row coordinates from niid data

- scripts/delete_records.py
Uses rethinkdb's `match` command to filter for records with field value
that matches the provided regex pattern. See rethinkdb docs for more
details: https://rethinkdb.com/api/python/match/
This was prompted by our need to delete flu sequence records that have
accessions with pattern "EPIEPI". We've fixed the accession with https://github.com/nextstrain/fauna/pull/148,
but we need to manually remove the old duplicate sequence records
because the flu sequence table uses the accession as the index.¹
¹ https://github.com/nextstrain/fauna/blob/ec1feb679715890ae6d14efe11c979f27d6f1d6f/vdb/upload.py#L82
> script/delete_records: Add option to match fields with regex pattern

- vdb/download.py
Allow users to define prioritized sequence accessions for a strain when the duplicate resolve method is `split_passage`. This flag could be extended for other resolve methods, but we are not actively using them in seasonal flu workflows so punting for now.
The file is expected to be a TSV file with a `strain` and `accession` column where the `strain` column only contains unique strain names. With the seasonal flu's pattern of downloading each segment separately,¹ the file should contain sequence accessions for a single segment.
¹ <https://github.com/nextstrain/seasonal-flu/blob/73b8294906da99a6abd26f543edd68dfd6e63d0e/workflow/snakemake_rules/download_from_fauna.smk#L69>
Part of https://github.com/nextstrain/fauna/issues/174
> vdb/download: Add `--prioritized_seqs_file` option

- vdb/flu_upload.py
Add `SPF\d` egg passage patterns to fix the passage categories for expected titer references that were reported missing on [Slack](https://bedfordlab.slack.com/archives/C03KWDET9/p1758316515093849?thread_ts=1758218156.298419&cid=C03KWDET9).
This should _not_ affect avian flu uploads since avian_flu_upload.py has it's own [format_passage method](https://github.com/nextstrain/fauna/blob/c5d8a28dd70918bcfcc8b9dc48fdf2f987be4124/vdb/avian_flu_upload.py#L618-L649).
> vdb/flu_upload: update passage patterns
